[package]
name = "constant_finite_field"
version = "0.1.0"
authors = ["Thijs Raymakers <thijs@raymakers.nl>"]
edition = "2018"
description = "Constant-time implementation of GF(2^8) arithmetic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
