[package]
name = "branch_free_finite_field"
version = "0.1.0"
authors = ["Thijs Raymakers <thijs@raymakers.nl>"]
edition = "2018"
description = "Branch-free implementation of GF(2^8) arithmetic"
categories = ["mathematics", "algorithms", "cryptography", "no-std", "science"]
license = "MIT"

[badges]
maintenance = { status = "passively-maintained" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
